import type { Metadata } from "next";
import { DM_Sans, Hanken_Grotesk } from "next/font/google";
import "./globals.css";

const DMSans = DM_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: "--font-dm-sans",
})

const HankenGrotesk = Hanken_Grotesk({  
  subsets: ['latin'],
  display: 'swap',
  variable: "--font-hanken-grotesk",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${DMSans.variable} ${HankenGrotesk.variable}`}>
      <body>{children}</body>
    </html>
  );
}
